config:
  partial_comment_separator: "\t"
  default_no_double_line: true
  default_yes_double_line: false
  object_yes_double_line: true
  force_single_line_until_item_count: null
  force_multi_line_from_item_count: null


exclusion_list:
  - "gfx"
  - "fonts"
  - "gui"
  - "input_profile"
  - "content_source"
  - "dlc"
  - "interface"
  - "licenses"
  - "localisation"
  - "music"
  - "notifications"
  - "sound"
  - "soundtrack"
  - "tools"
  - "credits.txt"
  - "checksum_manifest.txt"
  - "compound_settings.txt"
  - "settings_layout.txt"
  - "save_game_analysis.txt"
  - ".assets"
  - "coat_of_arms"
  - "common/history/states/"


special_words:
  if:
    object_yes_double_line: false
  when_taken:
    object_yes_double_line: false

special_folders:
  map_data:
    force_single_line_until_item_count: 10000

